name: ci/cd

on:
  push:
    branches: [master, 'release/**', 'feature/**', 'epic/**', 'task/**']
    tags: ['**']
  pull_request:
    branches: ['**']

jobs:

  build:
    name: Build on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [21, 22, 23, 24]
        os: [ubuntu-latest]
    
    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Download rebar3
      run: wget https://github.com/erlang/rebar3/releases/download/3.15.2/rebar3 && chmod 755 ./rebar3
    - name: Update Path
      run: echo "./" >> $GITHUB_PATH
    - name: Check rebar3 Version
      run: ./rebar3 --version
    - name: Compile
      run: rebar3 compile
