name: ci/cd

on:
  push:
    branches: [ master, release/*]
  pull_request:
    branches: [ master, release/*]

jobs:

  build:
    name: Build on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [21, 22, 23]
        os: [ubuntu-latest]
    
    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
